# fly.toml app configuration file generated for figma-prototype on 2023-11-27T21:00:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "figma-prototype"
primary_region = "gru"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
